<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$failures = [];

$expect = static function(bool $condition, string $message) use (&$failures): void {
	if (!$condition) $failures[] = $message;
};

$main = file_get_contents($root . '/Kern.module.php');
$service = file_get_contents($root . '/src/KernService.php');
$process = file_get_contents($root . '/ProcessKern.module.php');
foreach (glob($root . '/src/Admin/*.php') ?: [] as $adminSource) {
	$process .= file_get_contents($adminSource);
}
$database = file_get_contents($root . '/src/KernDatabase.php');
$policy = file_get_contents($root . '/src/KernAccessPolicy.php');
$rapid = file_get_contents($root . '/src/FieldAdapters/KernRapidAdapter.php');
$adminJs = file_get_contents($root . '/assets/js/admin.js');
$companyExample = file_get_contents($root . '/examples/company-directory/edit-company.php');

$expect(str_contains($main, "'pass'"), 'security field denylist is missing');
$expect(str_contains($main, 'revision_moderation'), 'revision moderation setting is missing');
$expect(str_contains($service, "hash_hmac('sha256'"), 'access codes are not HMAC hashed');
$expect(!str_contains($database, '`code_plain`'), 'database must not persist plaintext access codes');
$expect(str_contains($service, "'revision.conflict'"), 'revision conflict event is missing');
$expect(str_contains($service, '$this->db->transaction'), 'approved revisions are not transactional');
$expect(str_contains($database, 'kern_access_rules'), 'access-rule table is missing');
$expect(str_contains($policy, "'denies'"), 'access-rule deny support is missing');
$expect(str_contains($policy, "'claimants'"), 'claimant audience support is missing');
$expect(str_contains($policy, 'specific users') || str_contains($policy, "'users'"), 'specific-user access is missing');
$expect(str_contains($main, 'kern-manage-access'), 'access administration permission is missing');
$expect(str_contains($companyExample, 'submitRevision('), 'company example does not submit a Kern revision');
$expect(!str_contains($companyExample, '->save('), 'company example writes directly to a Page');
$expect(str_contains($main, "public const VERSION = 100"), 'Kern release version is not 100');
$expect(str_contains($main, "'version' => self::VERSION"), 'Kern version metadata is not linked to VERSION');
$expect(str_contains($process, "public const VERSION = 100"), 'ProcessKern release version is not 100');
$expect(str_contains($process, "'version' => self::VERSION"), 'ProcessKern version metadata is not linked to VERSION');
$expect(str_contains($process, "'Kern>=1.0.0'"), 'ProcessKern dependency does not match the 1.0.0 release');
$expect(str_contains(file_get_contents($root . '/ProcessKern.module.php'), 'use KernDashboardTrait;'), 'ProcessKern dashboard trait is not wired');
$expect(count(glob($root . '/src/Admin/*Trait.php') ?: []) === 7, 'ProcessKern admin trait set is incomplete');
$expect(str_contains($main, "'license' => 'MIT'"), 'Kern MIT metadata is missing');
$expect(str_contains($main, "'ProcessWire>=3.0.244'"), 'Kern ProcessWire requirement is not 3.0.244');
$expect(str_contains($main, "'PHP>=8.3'"), 'Kern PHP requirement is not 8.3');
$expect(str_contains($process, 'return $this->_(\'Fields not applicable\')'), 'Non-edit access rules do not explain that field scope is inapplicable');
$expect(str_contains($main, "get('InputfieldFieldset')"), 'module configuration is not grouped into native sections');
$expect(str_contains($main, 'kern_configuration_overview'), 'module configuration lacks policy context');
$expect(str_contains($main, 'KernConfigSummary'), 'module configuration lacks a compact policy summary');
$expect(str_contains($main, 'kern_default_scope'), 'module configuration lacks a clearly named default Page scope');
$expect(!str_contains($main, 'kern_legacy_scope'), 'module configuration still exposes legacy scope language');
$expect(str_contains($main, 'kern_data_lifecycle'), 'destructive uninstall settings are not isolated');
$expect(str_contains($main, "addBodyClass('ProcessKern')"), 'module configuration does not receive scoped responsive admin styles');
$expect(str_contains($service, '$forbidden'), 'force approval can bypass revoked field access');
$expect(str_contains($process, "get('InputfieldAsmSelect')"), 'access-rule editor does not use InputfieldAsmSelect');
$expect(str_contains($process, "get('InputfieldForm')"), 'access-rule editor does not use InputfieldForm');
$expect(str_contains($process, 'uk-subnav uk-subnav-pill KernTabs'), 'dashboard does not use shared native pill navigation');
$expect(str_contains($process, 'uk-card uk-card-default'), 'dashboard does not use native UIkit cards');
$expect(str_contains($process, 'KernQueueCard'), 'dashboard moderation queues are missing');
$expect(str_contains($process, 'KernRevisionCards'), 'responsive revision cards are missing');
$expect(str_contains($process, "'Review proposed Page changes'"), 'revision queue context is missing');
$expect(str_contains($process, 'KernRevisionQueueState'), 'revision workspace lacks an attention state');
$expect(str_contains($process, 'KernRevisionSummary'), 'revision workspace lacks a compact summary');
$expect(str_contains($process, 'KernRevisionSearch'), 'revision workspace lacks bounded search');
$expect(str_contains($process, "mb_stripos(\$haystack, \$query)"), 'workspace search does not inspect resolved context');
$expect(str_contains($process, "\$this->_('View revision')"), 'completed revisions do not expose a read-only action');
$expect(str_contains($process, "'claims shown'"), 'claim result summary is missing');
$expect(str_contains($process, 'KernTablePanel KernClaimTable'), 'claim table does not use the shared workspace panel');
$expect(!str_contains($process, 'uk-card uk-card-default uk-card-small KernClaimPanel'), 'claim list still uses the legacy card wrapper');
$expect(str_contains($process, 'KernFilterCount'), 'revision status counts are missing');
$expect(str_contains($process, 'uk-subnav-divider KernFilters KernFilterNav'), 'shared filters do not use divided navigation');
$expect(!str_contains($process, 'uk-subnav-pill KernFilters'), 'legacy pill filters are still rendered');
$expect(str_contains($process, 'aria-current="page"'), 'active filters do not expose their current-page state');
$expect(str_contains($process, 'KernReviewLayout'), 'revision detail review layout is missing');
$expect(str_contains($process, 'KernComparePane'), 'revision values are not presented as comparison panes');
$expect(str_contains($process, 'revisionModerationForm'), 'revision-specific decision panel is missing');
$expect(str_contains($process, "\$revision['status'] === 'conflict'"), 'force apply is not restricted to conflicting revisions');
$expect(str_contains($process, 'KernRawValue'), 'raw revision values cannot be disclosed on demand');
$expect(str_contains($process, 'revisionPageReferences'), 'Page references lack human-readable revision rendering');
$expect(str_contains($process, 'revisionTableRows'), 'Table revisions lack row-oriented rendering');
$expect(str_contains($process, 'KernDecisionSubmitterNote'), 'decision panel does not retain submitter context');
$expect(str_contains($process, 'KernClaimDetailIntro'), 'claim detail lacks a focused ownership header');
$expect(str_contains($process, 'KernClaimDetailSummary'), 'claim detail lacks a compact ownership summary');
$expect(str_contains($process, 'claimModerationPanel'), 'claim detail lacks status-aware moderation controls');
$expect(str_contains($process, "'pending' => ['approve', 'reject']"), 'pending claim decisions are not constrained');
$expect(str_contains($process, "'active' => ['revoke']"), 'active claim decisions are not constrained');
$expect(str_contains($service, "'active' => ['revoke']"), 'claim transition validation is not enforced by the service');
$expect(str_contains($process, 'KernRevisionDetailIntro'), 'revision detail lacks a focused context header');
$expect(str_contains($process, 'KernRevisionDetailSummary'), 'revision detail lacks a compact operational summary');
$expect(str_contains($process, 'KernChangeNumber'), 'revision changes lack a stable review sequence');
$expect(str_contains($process, 'KernRevisionHistorySummary'), 'revision history is not progressively disclosed');
$expect(str_contains($process, 'data-kern-open-details'), 'decision trail control does not target revision activity');
$expect(str_contains($adminJs, 'details.open = true'), 'decision trail control does not open the activity disclosure');
$expect(str_contains($process, "get('InputfieldPageAutocomplete')"), 'access-code form does not use native Page autocomplete');
$expect(str_contains($process, 'KernCodesLayout'), 'access-code workspace layout is missing');
$codeFormPosition = strpos($process, 'KernCodeFormAside');
$codeHistoryPosition = strpos($process, 'KernCodesMain');
$expect($codeFormPosition !== false && $codeHistoryPosition !== false && $codeFormPosition < $codeHistoryPosition, 'access-code creation is not the first workspace task');
$expect(str_contains($process, 'KernCodeCards'), 'responsive access-code cards are missing');
$expect(str_contains($process, 'KernCodeQueueState'), 'access-code workspace lacks delegated-access state');
$expect(str_contains($process, 'KernCodeSummary'), 'access-code workspace lacks a compact summary');
$expect(str_contains($process, 'KernCodeSearch'), 'access-code workspace lacks bounded search');
$expect(str_contains($process, "'closed' => \$this->_('Closed')"), 'access-code workspace lacks a closed-code filter');
$expect(str_contains($process, 'KernRevokeControl'), 'access-code revoke confirmation is missing');
$expect(str_contains($process, 'Redemptions left'), 'access-code capacity indicator is missing');
$expect(str_contains($process, 'KernVisuallyHidden'), 'Page autocomplete lacks an accessible search label');
$expect(str_contains($process, 'KernCodeSummary'), 'access-code indicators lack a compact mobile layout');
$expect(str_contains($process, 'has_parent!='), 'access-code Page search includes the ProcessWire admin tree');
$expect(str_contains($process, 'KernCodeSafetyNotice'), 'access-code form does not warn about one-time disclosure');
$expect(str_contains($process, 'Page availability currently follows'), 'access-code form does not explain Page policy scope');
$expect(str_contains($process, "\$this->_('Redemption limit')"), 'access-code redemption control has an unclear label');
$expect(str_contains($process, 'KernHistoryFilters'), 'audit history category filters are missing');
$expect(str_contains($process, 'KernHistoryCards'), 'responsive audit history cards are missing');
$expect(str_contains($process, 'KernHistoryCardDetails'), 'mobile audit details are not progressively disclosed');
$expect(str_contains($process, "'events shown'"), 'audit history result summary is missing');
$expect(str_contains($process, 'KernHistorySummary'), 'compact audit history summary is missing');
$expect(str_contains($process, 'KernHistorySearch'), 'audit history search is missing');
$expect(str_contains($process, "if (\$query !== '') \$params['q'] = \$query"), 'audit history filters do not preserve search context');
$expect(!str_contains($process, 'uk-card uk-card-default uk-card-small KernHistoryPanel'), 'audit history still uses the legacy card wrapper');
$expect(str_contains($process, 'historyEventLabel'), 'audit events lack human-readable labels');
$expect(str_contains($process, 'KernEventTechnical'), 'technical audit payloads cannot be disclosed on demand');
$expect(str_contains($process, 'KernClaimsWorkspace'), 'ownership claims lack a review workspace');
$expect(str_contains($process, 'KernClaimQueueState'), 'ownership claims lack a compact queue state');
$expect(str_contains($process, 'KernClaimSummary'), 'ownership claims lack a compact summary');
$expect(str_contains($process, 'KernClaimSearch'), 'ownership claims lack bounded search');
$expect(str_contains($process, "mb_stripos(\$haystack, \$query)"), 'ownership claim search does not inspect resolved Page and requester context');
$expect(str_contains($process, 'KernClaimCards'), 'responsive ownership claim cards are missing');
$expect(str_contains($process, 'decisions waiting') && str_contains($process, 'Review queue is clear'), 'ownership claims lack pending-decision context');
$expect(str_contains($process, 'claimSource'), 'ownership claim sources lack human-readable labels');
$expect(str_contains($process, "\$this->_('Requester')"), 'ownership claims do not lead with requester context');
$expect(str_contains($process, 'KernClaimId'), 'ownership claim IDs are not presented as secondary context');
$expect(str_contains($process, "\$this->_('View claim')"), 'closed ownership claims lack a clear view action');
$expect(str_contains($process, 'KernDashboardSummary'), 'dashboard indicators lack a compact operational summary');
$expect(str_contains($process, 'dashboardAttentionCard'), 'dashboard attention queue is missing');
$expect(str_contains($process, 'dashboardActivityList'), 'dashboard activity preview is not compact');
$expect(str_contains($process, 'KernDashboardClearState'), 'dashboard empty moderation queue is not compact');
$expect(str_contains($process, 'Legacy fallback is active'), 'dashboard does not disclose fallback policy readiness');
$expect(str_contains($process, 'KernDashboardHealth'), 'dashboard workflow health is missing');
$expect(str_contains($process, 'dashboardAccessSummary'), 'dashboard delegated-access summary is missing');
$expect(str_contains($process, 'KernDashboardAccessList'), 'dashboard access indicators are missing');
$expect(str_contains($process, 'KernDashboardAccessPanel'), 'dashboard access panel is not isolated from the access workspace summary');
$attentionPosition = strpos($process, '$out .= $this->dashboardAttentionCard(');
$statsPosition = strpos($process, 'KernDashboardSummary');
$expect($attentionPosition !== false && $statsPosition !== false && $attentionPosition < $statsPosition, 'dashboard moderation queue does not lead the operational content');
$activityPosition = strpos($process, 'KernActivityCard KernDashboardPanel');
$accessPosition = strpos($process, '$this->dashboardAccessSummary($counts');
$expect($activityPosition !== false && $accessPosition !== false && $activityPosition < $accessPosition, 'dashboard recent activity is not the primary operational panel');
$expect(str_contains($process, "'active_claims'"), 'dashboard does not expose active ownerships');
$expect(str_contains($process, "'enabled_rules'"), 'dashboard does not expose enabled access rules');
$expect(str_contains($process, "'active_codes' => [\$this->_('Active codes'), 'codes/?status=active', 'lock'"), 'delegated access uses an unsupported dashboard icon');
$expect(str_contains($process, 'codes/?status=active'), 'active-code indicator does not link to its exact filter');
$expect(str_contains($process, "history([], 6)"), 'dashboard activity preview is not bounded to six events');
$expect(str_contains($process, 'KernAccessWorkspace'), 'access rules lack a policy workspace');
$expect(str_contains($process, 'KernAccessCards'), 'responsive access-rule cards are missing');
$expect(str_contains($process, "'rules shown'"), 'access-rule result summary is missing');
$expect(str_contains($process, 'KernAccessQueueState'), 'access rules lack an explicit policy state');
$expect(str_contains($process, 'KernAccessSummary'), 'access rules lack a compact policy summary');
$expect(str_contains($process, 'KernAccessSearch'), 'access rules lack bounded search');
$expect(str_contains($process, 'Module defaults remain active'), 'empty access policy lacks default-policy context');
$expect(str_contains($process, 'KernTablePanel KernAccessTable'), 'access-rule table does not use the shared workspace panel');
$expect(!str_contains($process, 'uk-card uk-card-default uk-card-small KernAccessPanel'), 'access rules still use the legacy card wrapper');
$expect(str_contains($process, 'KernAccessRuleForm'), 'access-rule editor lacks a scoped native form');
$expect(str_contains($process, "'scope' => [\$this->_('2. Page and field scope')"), 'access-rule editor lacks a Page and field scope section');
$expect(str_contains($process, "'audience' => [\$this->_('3. Audience')"), 'access-rule editor lacks an audience section');
$expect(str_contains($process, "'permissions' => [\$this->_('4. Actions')"), 'access-rule editor lacks an actions section');
$expect(str_contains($process, 'KernAccessRuleGuidance'), 'access-rule editor does not explain matching and deny precedence');
$expect(str_contains($process, 'KernAccessRuleSummary'), 'access-rule editor lacks an impact summary');
$expect(str_contains($process, 'KernAccessRuleBreadth'), 'access-rule editor does not flag broad defaults');
$expect(str_contains($process, 'KernAccessRuleNotices'), 'access-rule editor guidance is not grouped responsively');
$expect(str_contains($process, 'Build an explicit access policy'), 'access-rule editor lacks a clear creation state');
$expect(str_contains($process, 'KernDeleteControl'), 'access-rule deletion lacks confirmation');
$expect(str_contains($process, 'Deny always wins'), 'access-rule deny precedence is not explained');
$adminCss = file_get_contents($root . '/assets/css/admin.css');
$expect(str_contains($adminCss, '.ProcessKern'), 'admin CSS is not scoped to ProcessKern');
$expect(str_contains($adminCss, '--pw-border-color'), 'admin CSS does not use ProcessWire design tokens');
$expect(str_contains($adminCss, '@media (max-width: 959px)'), 'revision queue lacks tablet/mobile layout');
$expect(str_contains($adminCss, '#pw-masthead.pw-masthead-hidden'), 'collapsed admin masthead can overflow the Kern workspace');
$expect(str_contains($adminCss, 'grid-template-columns: repeat(2, minmax(0, 1fr))'), 'mobile revision filters are not touch-friendly');
$expect(str_contains($adminCss, '.KernStructuredRows'), 'structured revision values lack readable row styling');
$expect(str_contains($adminCss, '.ProcessKern > .ui-autocomplete'), 'Page autocomplete results can overflow the access-code workspace');
$expect(!preg_match('/\\.ProcessKern \\.KernTablePanel\\s*\\{[^}]*padding-inline/s', $adminCss), 'table panels still add unnecessary inline padding');
$expect(str_contains($adminCss, '.ProcessKern .uk-button:visited'), 'Kern buttons can regain link underlines in visited states');
$expect(str_contains($adminCss, 'text-decoration: none !important'), 'AdminTheme link styles can override the Kern button-decoration reset');
$expect(!preg_match('/\.KernFilters\s*>\s*\.uk-active\s*>\s*a\s*\{[^}]*font-weight/s', $adminCss), 'active filters change label weight and cause layout shift');
$expect(preg_match('/\.KernFilterCount\s*\{[^}]*border-radius:\s*50%[^}]*height:\s*1\.75rem[^}]*width:\s*1\.75rem/s', $adminCss) === 1, 'filter counts are not fixed circles');
$expect(str_contains($rapid, 'toJSON'), 'Rapid public export lifecycle is not used');
$expect(str_contains($rapid, 'sanitizeValue'), 'Rapid public import lifecycle is not used');

if ($failures) {
	fwrite(STDERR, implode(PHP_EOL, $failures) . PHP_EOL);
	exit(1);
}

echo "Kern source smoke checks passed.\n";
